include:
  - board: lotus58_ble_left//zmk
    shield: nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: lotus58_ble_left
  - board: lotus58_ble_right//zmk
    shield: nice_view
    artifact-name: lotus58_ble_right
  - board: lotus58_ble_left//zmk
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
    artifact-name: lotus58_ble_left_reset
  - board: lotus58_ble_right//zmk
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_DISPLAY=n
    artifact-name: lotus58_ble_right_reset