# Sets the time before going into idle to 1 minute. (60 x 1000) ms
CONFIG_ZMK_IDLE_TIMEOUT=60000

# Enables deep sleep and sets the time before entering it to 30 minutes. (30 x 60 x 1000) ms
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Enables n-key rollover.
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Uncomment to enable the encoders.
# If you only have one encoder you don't need to change anything.
# Since the pins will not be connected they can just be ignored.
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment to enable the nice!view display.
# If you only have one display you need to create a separate .conf file in the same directory as this one.
# It should be named lotus58_ble_<left or right>.conf, depending on which half you put the display on.
# Copy the line below into the new .conf file and uncomment it there. Don't forget to add the shield to build.yaml.
CONFIG_ZMK_DISPLAY=y

# Uncomment to enable ZMK Studio support.
CONFIG_ZMK_STUDIO=y

# Uncomment to enable the underglow LEDs.
# They start turned off since the behavior is not persistent. Otherwise the LEDs start lit, even if you toggled them off before powering down.
CONFIG_ZMK_RGB_UNDERGLOW=y
#CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

# Uncomment to enable turning off underglow when idling.
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# Uncomment to enable right half indicator LED to mirror the left half. Currently broken in ZMK.
#CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y
