# ----- Hardware config -----
# In the hardware revision v1.00, v1.10 and v1.20 the wrong crystal (32.768MHz) is listed on the BOM.
# This enables the RC oscillator of the nRF52840 as a replacement.
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# If you replaced it with the correct one as stated by the nRF52840 datasheet (32.768KHz) you can disable the above code and enable the lines below.
# Don't forget to set the frequency stability to the value of the crystal you bought.
#CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
#CONFIG_CLOCK_CONTROL_NRF_K32SRC_20PPM=y

# Disables external power cut when toggling underglow. Can be removed once the PCB design error is fixed.
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Uncomment to enable cutting the power to the LEDs via keypress. Currently not functional due to a PCB design error.
#CONFIG_ZMK_EXT_POWER=y



# ----- Software config -----
# Sets the time before going into idle to 1 minute. (60 x 1000)ms
CONFIG_ZMK_IDLE_TIMEOUT=6000

# Enables deep sleep and sets the time before entering it to 30 minutes. (30 x 60 x 1000)ms
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Enables n-key rollover.
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Uncomment to enable the encoders.
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment to enable the nice!view display.
CONFIG_ZMK_DISPLAY=y

# Uncomment to enable ZMK Studio support.
CONFIG_ZMK_STUDIO=y

# Uncomment to enable the underglow LEDs.
CONFIG_ZMK_RGB_UNDERGLOW=y

# Uncomment to enable right half indicator LED to mirror the left half. Currently broken in ZMK.
#CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y
